### ISSUE TITLE
Format check is no longer failing on improper format

### ISSUE THREAD

**Issue by stephen99scott** [adambujak/SignBuddy#44]
* Format check on master showed no errors:
![image](https://user-images.githubusercontent.com/55762060/142511442-2eac20d0-91c8-4d3d-9066-09e04061aa5c.png)
* Pulling master and running the formatter shows that there is a formatting change to be made in the testing directory
![image](https://user-images.githubusercontent.com/55762060/142511367-73c31b10-6c47-491b-ae44-68715e48282d.png)
* Do we want the formatter to also check the format of tests?

**Comment by adambujak** [comment]
closed with #45
