### ISSUE TITLE
investigate why i2c reads from imu are so slow

### ISSUE THREAD

**Issue by adambujak** [adambujak/SignBuddy#63]

**Comment by adambujak** [comment]
ERR_CHECK(bno055_set_operation_mode(BNO055_OPERATION_MODE_AMG));

this line in `get_data` is causing ~600ms of delay

**Comment by adambujak** [comment]
@harneetMac what does this line do

**Comment by stephen99scott** [comment]
Any update on this issue?

**Comment by stephen99scott** [comment]
Closed with [1fdbb01](https://github.com/adambujak/SignBuddy/pull/78/commits/1fdbb01a1ce9d9b3927df542c0179927eb652856)
